/**
 * Pure HTML builder for the export PDF. Kept free of Playwright so it can be
 * unit-tested without a browser. `pdf-renderer.ts` feeds this HTML to chromium.
 */
import { DEFAULT_LAYERS } from '@planiq/shared';

export interface FloorData {
  floor: any;
  rasterUrl: string | null;
  placements: any[];
  layers: any[];
}

export interface RenderInput {
  project: any;
  floors: FloorData[];
  devices: any[];
  options: any;
  preparedBy?: string | null;
}

// Persisted layer docs usually omit `categories`; fall back to matching the
// layer name against the default catalog so layer visibility is respected.
const LAYER_CATS_BY_NAME: Record<string, string[]> =
  Object.fromEntries(DEFAULT_LAYERS.map((l) => [l.name, l.categories]));

export function esc(s: any) {
  return String(s ?? '').replace(/[&<>"]/g, (c) => ({ '&': '&amp;', '<': '&lt;', '>': '&gt;', '"': '&quot;' }[c]!));
}

/** A device is shown in the export only if it is accepted, visible, and on a visible layer. */
function isVisible(p: any, layers: any[], byCode: Map<string, any>): boolean {
  if (p.hidden) return false;
  const rejected = p?.meta?.qcStatus === 'rejected' || (p.confidence != null && p.confidence < 0.62);
  if (rejected) return false;
  const cat = byCode.get(p.deviceCode)?.category ?? '';
  const lyr = layers.find((l) => (l.categories ?? LAYER_CATS_BY_NAME[l.name] ?? []).includes(cat));
  if (lyr && lyr.visible === false) return false;
  return true;
}

export function buildHtml({ project, floors, devices, options, preparedBy }: RenderInput): string {
  const byCode = new Map<string, any>(devices.map((d: any) => [d.code, d]));
  const today = new Date().toLocaleDateString('en-GB', { day: '2-digit', month: 'short', year: 'numeric' });
  const style: string = options?.style === 'detailed' ? 'detailed' : 'standard';
  const clientName = options?.clientName ?? project?.client?.name ?? '—';

  // Precompute the visible device set per floor — used consistently by markers,
  // legend, schedule and counts.
  const floorViews = floors.map((f) => {
    const visible = f.placements.filter((p) => isVisible(p, f.layers ?? [], byCode));
    return { ...f, visible };
  });

  const totalDevices = floorViews.reduce((n, f) => n + f.visible.length, 0);
  const usedCodes = new Set<string>();
  floorViews.forEach((f) => f.visible.forEach((p) => usedCodes.add(p.deviceCode)));

  const CATEGORY_LABELS: Record<string, string> = {
    cctv: 'CCTV & Surveillance', network: 'Network / Wi-Fi', elv: 'ELV',
    access: 'Access / Intercom', smart_home: 'Smart Home', audio: 'Audio / AV', annotation: 'Annotations',
  };
  const categoryOf = (code: string) => byCode.get(code)?.category ?? 'other';

  // ── Legend (grouped by category) ──
  function legendHtml(codes: Set<string>): string {
    const byCat = new Map<string, string[]>();
    [...codes].forEach((code) => {
      const cat = categoryOf(code);
      if (!byCat.has(cat)) byCat.set(cat, []);
      byCat.get(cat)!.push(code);
    });
    const groups = [...byCat.entries()].map(([cat, codes]) => {
      const items = codes
        .sort((a, b) => (byCode.get(a)?.order ?? 0) - (byCode.get(b)?.order ?? 0))
        .map((code) => {
          const d = byCode.get(code) ?? { name: code, color: '#334155' };
          return `<div class="lg"><span class="dot" style="background:${esc(d.color)}"></span>${esc(d.name)}</div>`;
        }).join('');
      return `<div class="lg-group"><div class="lg-cat">${esc(CATEGORY_LABELS[cat] ?? cat)}</div><div class="lg-items">${items}</div></div>`;
    }).join('');
    return `<div class="legend">${groups}</div>`;
  }

  // ── Cover ──
  const cover = `
    <section class="page cover">
      <div class="cover-top">
        <div class="brand">PlanIQ</div>
        <div class="cover-sub">Smart-Home · ELV · CCTV · Network — Device Layout</div>
      </div>
      <div class="cover-mid">
        <h1>${esc(project?.name ?? 'Project')}</h1>
        ${project?.code ? `<div class="proj-code">${esc(project.code)}</div>` : ''}
      </div>
      <table class="meta">
        <tr><td>Client</td><td>${esc(clientName)}</td></tr>
        <tr><td>Contact</td><td>${esc(project?.client?.contact ?? '—')} ${esc(project?.client?.phone ?? '')}</td></tr>
        <tr><td>Address</td><td>${esc(project?.client?.address ?? '—')}</td></tr>
        <tr><td>Floors</td><td>${floorViews.length}</td></tr>
        <tr><td>Devices</td><td>${totalDevices}</td></tr>
        ${options?.versionName ? `<tr><td>Revision</td><td>${esc(options.versionName)}</td></tr>` : ''}
        <tr><td>Prepared by</td><td>${esc(preparedBy ?? 'PlanIQ')} · PlanIQ</td></tr>
        <tr><td>Date</td><td>${esc(today)}</td></tr>
      </table>
      ${options?.notes ? `<div class="notes"><b>Notes</b><p>${esc(options.notes)}</p></div>` : ''}
      <div class="cover-foot">This document was generated by PlanIQ. All device placements are reviewable and editable by the project engineer.</div>
    </section>`;

  // ── Floor pages ──
  const floorPages = floorViews.map((f: any) => {
    const markers = f.visible.map((p: any) => {
      const d: any = byCode.get(p.deviceCode) ?? { color: '#E11D2A' };
      return `<div class="marker" style="left:${(p.position.x * 100).toFixed(2)}%;top:${(p.position.y * 100).toFixed(2)}%;border-color:${esc(d.color)}">
        <span class="pin" style="background:${esc(d.color)};transform:rotate(${Number(p.rotation) || 0}deg)"></span>
        <span class="mlabel">${esc(p.label ?? d.name ?? p.deviceCode)}</span></div>`;
    }).join('');
    const rev = f.floor?.analysis?.version ? `Rev. ${f.floor.analysis.version}` : '';
    const codes = new Set<string>(f.visible.map((p: any) => p.deviceCode));
    return `
      <section class="page floor">
        <header class="title-block">
          <div class="tb-left">
            <div class="tb-project">${esc(project?.name ?? 'Project')}</div>
            <h2>${esc(f.floor.name)}</h2>
            <div class="tb-meta">${esc(f.floor.kind ?? '')} · level ${esc(f.floor.level ?? 0)}</div>
          </div>
          <div class="tb-right">
            <div><span>Devices</span><b>${f.visible.length}</b></div>
            <div><span>Date</span><b>${esc(today)}</b></div>
            ${rev ? `<div><span>Version</span><b>${esc(rev)}</b></div>` : ''}
            <div class="tb-brand">PlanIQ</div>
          </div>
        </header>
        <div class="canvas">
          ${f.rasterUrl ? `<img src="${esc(f.rasterUrl)}" />` : '<div class="noimg">No plan image available</div>'}
          ${markers}
        </div>
        ${options?.includeLegend !== false ? legendHtml(codes) : ''}
      </section>${style === 'detailed' ? deviceDetailPage(f) : ''}`;
  }).join('');

  // ── Detailed style: per-floor device schedule with location, confidence, rationale ──
  function deviceDetailPage(f: any): string {
    if (!f.visible.length) return '';
    const rows = f.visible
      .slice()
      .sort((a: any, b: any) => (byCode.get(a.deviceCode)?.order ?? 0) - (byCode.get(b.deviceCode)?.order ?? 0))
      .map((p: any) => {
        const d: any = byCode.get(p.deviceCode) ?? { name: p.deviceCode, color: '#334155' };
        const conf = p.confidence != null ? `${Math.round(p.confidence * 100)}%` : '—';
        return `<tr>
          <td><span class="dot" style="background:${esc(d.color)}"></span>${esc(d.name)}</td>
          <td>${esc(p.label ?? '')}</td>
          <td>${esc(p?.meta?.nearSpace ?? '')}</td>
          <td class="num">${conf}</td>
          <td class="rat">${esc(p.rationale ?? '')}</td>
        </tr>`;
      }).join('');
    return `<section class="page schedule">
      <header class="title-block"><div class="tb-left"><div class="tb-project">${esc(project?.name ?? 'Project')}</div><h2>${esc(f.floor.name)} — Device details</h2></div>
      <div class="tb-right"><div><span>Devices</span><b>${f.visible.length}</b></div><div class="tb-brand">PlanIQ</div></div></header>
      <table class="sched"><thead><tr><th>Device</th><th>Label</th><th>Location</th><th class="num">Conf.</th><th>Rationale</th></tr></thead><tbody>${rows}</tbody></table>
    </section>`;
  }

  // ── AI analysis summary (optional) ──
  const aiSummary = options?.includeAiSummary === false ? '' : (() => {
    const rows = floorViews.map((f: any) => {
      const a = f.floor?.analysis ?? {};
      const q = a.qcSummary ?? {};
      const conf = typeof a.confidence === 'number' ? `${Math.round(a.confidence * 100)}%` : '—';
      return `<tr><td>${esc(f.floor.name)}</td><td class="num">${conf}</td><td class="num">${q.acceptedPlacements ?? f.visible.length}</td><td class="num">${q.rejectedPlacements ?? 0}</td><td class="num">${q.detectedSpaces ?? f.floor?.counts?.rooms ?? '—'}</td></tr>`;
    }).join('');
    const accepted = floorViews.reduce((n: number, f: any) => n + (f.floor?.analysis?.qcSummary?.acceptedPlacements ?? f.visible.length), 0);
    const rejected = floorViews.reduce((n: number, f: any) => n + (f.floor?.analysis?.qcSummary?.rejectedPlacements ?? 0), 0);
    return `<section class="page schedule">
      <header class="title-block"><div class="tb-left"><div class="tb-project">${esc(project?.name ?? 'Project')}</div><h2>AI Analysis Summary</h2></div>
      <div class="tb-right"><div><span>Accepted</span><b>${accepted}</b></div><div><span>Rejected</span><b>${rejected}</b></div><div class="tb-brand">PlanIQ</div></div></header>
      <p class="ai-note">Confidence reflects the computer-vision room-detection certainty per floor. Every device suggestion was reviewed and is fully editable; rejected items were withheld by the quality-control layer and are not shown.</p>
      <table class="sched"><thead><tr><th>Floor</th><th class="num">Confidence</th><th class="num">Accepted</th><th class="num">Rejected</th><th class="num">Spaces</th></tr></thead><tbody>${rows}</tbody></table>
    </section>`;
  })();

  // ── Device schedule (grouped by category, per project) ──
  const schedule = options?.includeSchedule === false ? '' : (() => {
    const byCat = new Map<string, string[]>();
    [...usedCodes].forEach((code) => {
      const cat = categoryOf(code);
      if (!byCat.has(cat)) byCat.set(cat, []);
      byCat.get(cat)!.push(code);
    });
    const sections = [...byCat.entries()].map(([cat, codes]) => {
      let catTotal = 0;
      const rows = codes
        .sort((a, b) => (byCode.get(a)?.order ?? 0) - (byCode.get(b)?.order ?? 0))
        .map((code) => {
          const total = floorViews.reduce((n, f: any) => n + f.visible.filter((p: any) => p.deviceCode === code).length, 0);
          catTotal += total;
          const d: any = byCode.get(code) ?? { name: code, color: '#334155' };
          return `<tr><td><span class="dot" style="background:${esc(d.color)}"></span>${esc(d.name)}</td><td class="num">${total}</td></tr>`;
        }).join('');
      return `<tbody class="sched-cat">
        <tr class="cat-row"><td>${esc(CATEGORY_LABELS[cat] ?? cat)}</td><td class="num">${catTotal}</td></tr>
        ${rows}</tbody>`;
    }).join('');
    return `<section class="page schedule">
      <header class="title-block"><div class="tb-left"><div class="tb-project">${esc(project?.name ?? 'Project')}</div><h2>Device Schedule</h2></div>
      <div class="tb-right"><div><span>Total devices</span><b>${totalDevices}</b></div><div class="tb-brand">PlanIQ</div></div></header>
      <table class="sched"><thead><tr><th>Device</th><th class="num">Qty</th></tr></thead>${sections}
      <tfoot><tr><td>Grand total</td><td class="num">${totalDevices}</td></tr></tfoot></table>
    </section>`;
  })();

  return `<!doctype html><html><head><meta charset="utf-8"><style>
    * { box-sizing: border-box; font-family: Inter, Arial, sans-serif; -webkit-print-color-adjust: exact; }
    body { margin: 0; color: #0f172a; }
    .page { page-break-after: always; padding: 6mm 4mm; }
    .page:last-child { page-break-after: auto; }

    /* Cover */
    .cover { display:flex; flex-direction:column; gap:18px; height:100%; }
    .cover-top { border-bottom:3px solid #E11D2A; padding-bottom:10px; }
    .brand { color:#E11D2A; font-weight:800; letter-spacing:3px; font-size:24px; }
    .cover-sub { color:#64748b; font-size:12px; letter-spacing:1px; margin-top:4px; }
    .cover-mid { margin-top:8px; }
    .cover h1 { font-size:38px; margin:0; }
    .proj-code { color:#64748b; font-size:14px; margin-top:6px; letter-spacing:1px; }
    .meta { border-collapse:collapse; max-width:560px; }
    .meta td { border-bottom:1px solid #e2e8f0; padding:9px 14px; font-size:13px; }
    .meta td:first-child { color:#64748b; width:160px; font-weight:600; }
    .notes { background:#f8fafc; border-left:4px solid #E11D2A; padding:12px 16px; max-width:680px; font-size:12px; }
    .cover-foot { margin-top:auto; color:#94a3b8; font-size:10px; border-top:1px solid #e2e8f0; padding-top:10px; }

    /* Title block (floor + schedule) */
    .title-block { display:flex; justify-content:space-between; align-items:flex-start; border-bottom:2px solid #0f172a; padding-bottom:8px; margin-bottom:10px; }
    .tb-project { color:#64748b; font-size:11px; text-transform:uppercase; letter-spacing:1px; }
    .title-block h2 { font-size:22px; margin:2px 0 0; }
    .tb-meta { color:#64748b; font-size:11px; text-transform:capitalize; margin-top:2px; }
    .tb-right { display:flex; gap:18px; align-items:flex-end; }
    .tb-right > div { text-align:right; }
    .tb-right span { display:block; color:#94a3b8; font-size:9px; text-transform:uppercase; letter-spacing:.5px; }
    .tb-right b { font-size:14px; }
    .tb-brand { color:#E11D2A; font-weight:800; letter-spacing:2px; font-size:16px; }

    /* Floor canvas */
    .canvas { position:relative; border:1px solid #e2e8f0; background:#fff; }
    .canvas img { width:100%; display:block; }
    .noimg { padding:120px; text-align:center; color:#94a3b8; }
    .marker { position:absolute; transform:translate(-50%,-50%); display:flex; flex-direction:column; align-items:center; gap:1px; }
    .marker .pin { width:11px; height:11px; border-radius:3px; border:1.5px solid #fff; box-shadow:0 0 0 1px rgba(0,0,0,.25); display:block; }
    .marker .mlabel { font-size:7px; font-weight:600; color:#0f172a; background:rgba(255,255,255,.85); padding:0 2px; border-radius:2px; white-space:nowrap; }

    /* Legend */
    .legend { display:flex; flex-wrap:wrap; gap:10px 26px; margin-top:12px; padding-top:10px; border-top:1px dashed #cbd5e1; }
    .lg-group { min-width:150px; }
    .lg-cat { font-size:10px; font-weight:700; text-transform:uppercase; letter-spacing:.5px; color:#475569; margin-bottom:4px; }
    .lg-items { display:flex; flex-direction:column; gap:3px; }
    .lg { display:flex; align-items:center; gap:7px; font-size:11px; }
    .dot { width:11px; height:11px; border-radius:3px; display:inline-block; flex:0 0 auto; }

    /* Schedule */
    table.sched { width:100%; border-collapse:collapse; }
    .sched th, .sched td { text-align:left; padding:7px 10px; border-bottom:1px solid #e2e8f0; font-size:12px; }
    .sched th { background:#0f172a; color:#fff; }
    .sched .num { text-align:right; width:90px; }
    .sched td .dot { margin-right:8px; vertical-align:middle; }
    .cat-row td { background:#f1f5f9; font-weight:700; }
    .sched tfoot td { font-weight:800; border-top:2px solid #0f172a; background:#fff; }
    .sched .rat { color:#475569; font-size:11px; max-width:380px; }
    .ai-note { color:#64748b; font-size:11px; margin:10px 0 6px; max-width:760px; }
  </style></head><body>${cover}${floorPages}${aiSummary}${schedule}</body></html>`;
}
