import { chromium } from 'playwright';
import { buildHtml, esc, RenderInput } from './pdf-html';

export type { RenderInput, FloorData } from './pdf-html';

/** Build a client-ready PDF: cover + one page per floor (raster + device overlay + legend) + device schedule. */
export async function renderProjectPdf(input: RenderInput): Promise<Buffer> {
  const html = buildHtml(input);
  const browser = await chromium.launch({ args: ['--no-sandbox'] });
  try {
    const page = await browser.newPage();
    await page.setContent(html, { waitUntil: 'networkidle' });
    const footer = `
      <div style="font-size:7px;color:#94a3b8;font-family:Arial,sans-serif;width:100%;padding:0 12mm;display:flex;justify-content:space-between;align-items:center;">
        <span>${esc(input.project?.name ?? 'PlanIQ Project')}</span>
        <span>Generated by PlanIQ</span>
        <span>Page <span class="pageNumber"></span> / <span class="totalPages"></span></span>
      </div>`;
    const pdf = await page.pdf({
      format: 'A3',
      landscape: true,
      printBackground: true,
      displayHeaderFooter: true,
      headerTemplate: '<span></span>',
      footerTemplate: footer,
      margin: { top: '12mm', bottom: '16mm', left: '10mm', right: '10mm' },
    });
    return pdf;
  } finally {
    await browser.close();
  }
}
